services:
  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.27.3
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      QUERY_DEFAULTS_LIMIT: "20"
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      DEFAULT_VECTORIZER_MODULE: "none"
      ENABLE_MODULES: ""
      CLUSTER_HOSTNAME: "node1"

  opa:
    image: openpolicyagent/opa:0.67.1
    command: ["run", "--server", "--addr", "0.0.0.0:8181", "/policies/policy.rego"]
    volumes:
      - ./opa:/policies:ro
    ports:
      - "8181:8181"
